# Generated by Django 3.2 on 2021-04-20 08:44

from django.db import migrations



class Migration(migrations.Migration):

    def create_profiles(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        Profile = apps.get_model('accounts', 'Profile')
        for user in User.objects.all():
            Profile.objects.get_or_create(user=user)

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop)
    ]
