# Generated by Django 3.1.7 on 2021-04-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210420_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
