# Generated by Django 3.1.7 on 2021-04-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210402_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', to='webapp.category', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Корзины',
                'db_table': 'carts',
            },
        ),
    ]
