# Generated by Django 3.1.7 on 2021-05-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210426_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
    ]
